// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/stats.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_stats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{0}
}

type ListenSocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Pid           uint32                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	User          string                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Port          uint64                 `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenSocket) Reset() {
	*x = ListenSocket{}
	mi := &file_proto_stats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenSocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenSocket) ProtoMessage() {}

func (x *ListenSocket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenSocket.ProtoReflect.Descriptor instead.
func (*ListenSocket) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{1}
}

func (x *ListenSocket) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ListenSocket) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *ListenSocket) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ListenSocket) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListenSocket) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

type FSStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filesystem    string                 `protobuf:"bytes,1,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	MountPoint    string                 `protobuf:"bytes,2,opt,name=mount_point,json=mountPoint,proto3" json:"mount_point,omitempty"`
	UsedMb        uint64                 `protobuf:"varint,3,opt,name=used_mb,json=usedMb,proto3" json:"used_mb,omitempty"`
	UsedPerc      float64                `protobuf:"fixed64,4,opt,name=used_perc,json=usedPerc,proto3" json:"used_perc,omitempty"`
	UsedInode     uint64                 `protobuf:"varint,5,opt,name=used_inode,json=usedInode,proto3" json:"used_inode,omitempty"`
	InodePerc     float64                `protobuf:"fixed64,6,opt,name=inode_perc,json=inodePerc,proto3" json:"inode_perc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSStat) Reset() {
	*x = FSStat{}
	mi := &file_proto_stats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSStat) ProtoMessage() {}

func (x *FSStat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSStat.ProtoReflect.Descriptor instead.
func (*FSStat) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{2}
}

func (x *FSStat) GetFilesystem() string {
	if x != nil {
		return x.Filesystem
	}
	return ""
}

func (x *FSStat) GetMountPoint() string {
	if x != nil {
		return x.MountPoint
	}
	return ""
}

func (x *FSStat) GetUsedMb() uint64 {
	if x != nil {
		return x.UsedMb
	}
	return 0
}

func (x *FSStat) GetUsedPerc() float64 {
	if x != nil {
		return x.UsedPerc
	}
	return 0
}

func (x *FSStat) GetUsedInode() uint64 {
	if x != nil {
		return x.UsedInode
	}
	return 0
}

func (x *FSStat) GetInodePerc() float64 {
	if x != nil {
		return x.InodePerc
	}
	return 0
}

type ProtoTalker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Proto         string                 `protobuf:"bytes,1,opt,name=proto,proto3" json:"proto,omitempty"`
	Bytes         uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Perc          float64                `protobuf:"fixed64,3,opt,name=perc,proto3" json:"perc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtoTalker) Reset() {
	*x = ProtoTalker{}
	mi := &file_proto_stats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtoTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtoTalker) ProtoMessage() {}

func (x *ProtoTalker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtoTalker.ProtoReflect.Descriptor instead.
func (*ProtoTalker) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{3}
}

func (x *ProtoTalker) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *ProtoTalker) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *ProtoTalker) GetPerc() float64 {
	if x != nil {
		return x.Perc
	}
	return 0
}

type FlowTalker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           string                 `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           string                 `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Proto         string                 `protobuf:"bytes,3,opt,name=proto,proto3" json:"proto,omitempty"`
	Bps           uint64                 `protobuf:"varint,4,opt,name=bps,proto3" json:"bps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlowTalker) Reset() {
	*x = FlowTalker{}
	mi := &file_proto_stats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowTalker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowTalker) ProtoMessage() {}

func (x *FlowTalker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowTalker.ProtoReflect.Descriptor instead.
func (*FlowTalker) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{4}
}

func (x *FlowTalker) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *FlowTalker) GetDst() string {
	if x != nil {
		return x.Dst
	}
	return ""
}

func (x *FlowTalker) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *FlowTalker) GetBps() uint64 {
	if x != nil {
		return x.Bps
	}
	return 0
}

type Snapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Load          float64                `protobuf:"fixed64,1,opt,name=load,proto3" json:"load,omitempty"`
	CpuUser       float64                `protobuf:"fixed64,2,opt,name=cpu_user,json=cpuUser,proto3" json:"cpu_user,omitempty"`
	CpuSys        float64                `protobuf:"fixed64,3,opt,name=cpu_sys,json=cpuSys,proto3" json:"cpu_sys,omitempty"`
	CpuIdle       float64                `protobuf:"fixed64,4,opt,name=cpu_idle,json=cpuIdle,proto3" json:"cpu_idle,omitempty"`
	DiskTps       float64                `protobuf:"fixed64,5,opt,name=disk_tps,json=diskTps,proto3" json:"disk_tps,omitempty"`
	DiskKbs       float64                `protobuf:"fixed64,6,opt,name=disk_kbs,json=diskKbs,proto3" json:"disk_kbs,omitempty"`
	TcpStates     map[string]int64       `protobuf:"bytes,7,rep,name=tcp_states,json=tcpStates,proto3" json:"tcp_states,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Fs            []*FSStat              `protobuf:"bytes,8,rep,name=fs,proto3" json:"fs,omitempty"`
	ProtoTop      []*ProtoTalker         `protobuf:"bytes,9,rep,name=ProtoTop,proto3" json:"ProtoTop,omitempty"`
	FlowTop       []*FlowTalker          `protobuf:"bytes,10,rep,name=FlowTop,proto3" json:"FlowTop,omitempty"`
	Listen        []*ListenSocket        `protobuf:"bytes,11,rep,name=Listen,proto3" json:"Listen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_proto_stats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_proto_stats_proto_rawDescGZIP(), []int{5}
}

func (x *Snapshot) GetLoad() float64 {
	if x != nil {
		return x.Load
	}
	return 0
}

func (x *Snapshot) GetCpuUser() float64 {
	if x != nil {
		return x.CpuUser
	}
	return 0
}

func (x *Snapshot) GetCpuSys() float64 {
	if x != nil {
		return x.CpuSys
	}
	return 0
}

func (x *Snapshot) GetCpuIdle() float64 {
	if x != nil {
		return x.CpuIdle
	}
	return 0
}

func (x *Snapshot) GetDiskTps() float64 {
	if x != nil {
		return x.DiskTps
	}
	return 0
}

func (x *Snapshot) GetDiskKbs() float64 {
	if x != nil {
		return x.DiskKbs
	}
	return 0
}

func (x *Snapshot) GetTcpStates() map[string]int64 {
	if x != nil {
		return x.TcpStates
	}
	return nil
}

func (x *Snapshot) GetFs() []*FSStat {
	if x != nil {
		return x.Fs
	}
	return nil
}

func (x *Snapshot) GetProtoTop() []*ProtoTalker {
	if x != nil {
		return x.ProtoTop
	}
	return nil
}

func (x *Snapshot) GetFlowTop() []*FlowTalker {
	if x != nil {
		return x.FlowTop
	}
	return nil
}

func (x *Snapshot) GetListen() []*ListenSocket {
	if x != nil {
		return x.Listen
	}
	return nil
}

var File_proto_stats_proto protoreflect.FileDescriptor

const file_proto_stats_proto_rawDesc = "" +
	"\n" +
	"\x11proto/stats.proto\x12\x05stats\"\a\n" +
	"\x05Empty\"~\n" +
	"\fListenSocket\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\rR\x03pid\x12\x12\n" +
	"\x04user\x18\x03 \x01(\tR\x04user\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x04R\x04port\"\xbd\x01\n" +
	"\x06FSStat\x12\x1e\n" +
	"\n" +
	"filesystem\x18\x01 \x01(\tR\n" +
	"filesystem\x12\x1f\n" +
	"\vmount_point\x18\x02 \x01(\tR\n" +
	"mountPoint\x12\x17\n" +
	"\aused_mb\x18\x03 \x01(\x04R\x06usedMb\x12\x1b\n" +
	"\tused_perc\x18\x04 \x01(\x01R\busedPerc\x12\x1d\n" +
	"\n" +
	"used_inode\x18\x05 \x01(\x04R\tusedInode\x12\x1d\n" +
	"\n" +
	"inode_perc\x18\x06 \x01(\x01R\tinodePerc\"M\n" +
	"\vProtoTalker\x12\x14\n" +
	"\x05proto\x18\x01 \x01(\tR\x05proto\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\x12\x12\n" +
	"\x04perc\x18\x03 \x01(\x01R\x04perc\"X\n" +
	"\n" +
	"FlowTalker\x12\x10\n" +
	"\x03src\x18\x01 \x01(\tR\x03src\x12\x10\n" +
	"\x03dst\x18\x02 \x01(\tR\x03dst\x12\x14\n" +
	"\x05proto\x18\x03 \x01(\tR\x05proto\x12\x10\n" +
	"\x03bps\x18\x04 \x01(\x04R\x03bps\"\xc9\x03\n" +
	"\bSnapshot\x12\x12\n" +
	"\x04load\x18\x01 \x01(\x01R\x04load\x12\x19\n" +
	"\bcpu_user\x18\x02 \x01(\x01R\acpuUser\x12\x17\n" +
	"\acpu_sys\x18\x03 \x01(\x01R\x06cpuSys\x12\x19\n" +
	"\bcpu_idle\x18\x04 \x01(\x01R\acpuIdle\x12\x19\n" +
	"\bdisk_tps\x18\x05 \x01(\x01R\adiskTps\x12\x19\n" +
	"\bdisk_kbs\x18\x06 \x01(\x01R\adiskKbs\x12=\n" +
	"\n" +
	"tcp_states\x18\a \x03(\v2\x1e.stats.Snapshot.TcpStatesEntryR\ttcpStates\x12\x1d\n" +
	"\x02fs\x18\b \x03(\v2\r.stats.FSStatR\x02fs\x12.\n" +
	"\bProtoTop\x18\t \x03(\v2\x12.stats.ProtoTalkerR\bProtoTop\x12+\n" +
	"\aFlowTop\x18\n" +
	" \x03(\v2\x11.stats.FlowTalkerR\aFlowTop\x12+\n" +
	"\x06Listen\x18\v \x03(\v2\x13.stats.ListenSocketR\x06Listen\x1a<\n" +
	"\x0eTcpStatesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x012>\n" +
	"\fStatsService\x12.\n" +
	"\vStreamStats\x12\f.stats.Empty\x1a\x0f.stats.Snapshot0\x01B\x0fZ\rvsysmon/protob\x06proto3"

var (
	file_proto_stats_proto_rawDescOnce sync.Once
	file_proto_stats_proto_rawDescData []byte
)

func file_proto_stats_proto_rawDescGZIP() []byte {
	file_proto_stats_proto_rawDescOnce.Do(func() {
		file_proto_stats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)))
	})
	return file_proto_stats_proto_rawDescData
}

var file_proto_stats_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_stats_proto_goTypes = []any{
	(*Empty)(nil),        // 0: stats.Empty
	(*ListenSocket)(nil), // 1: stats.ListenSocket
	(*FSStat)(nil),       // 2: stats.FSStat
	(*ProtoTalker)(nil),  // 3: stats.ProtoTalker
	(*FlowTalker)(nil),   // 4: stats.FlowTalker
	(*Snapshot)(nil),     // 5: stats.Snapshot
	nil,                  // 6: stats.Snapshot.TcpStatesEntry
}
var file_proto_stats_proto_depIdxs = []int32{
	6, // 0: stats.Snapshot.tcp_states:type_name -> stats.Snapshot.TcpStatesEntry
	2, // 1: stats.Snapshot.fs:type_name -> stats.FSStat
	3, // 2: stats.Snapshot.ProtoTop:type_name -> stats.ProtoTalker
	4, // 3: stats.Snapshot.FlowTop:type_name -> stats.FlowTalker
	1, // 4: stats.Snapshot.Listen:type_name -> stats.ListenSocket
	0, // 5: stats.StatsService.StreamStats:input_type -> stats.Empty
	5, // 6: stats.StatsService.StreamStats:output_type -> stats.Snapshot
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_stats_proto_init() }
func file_proto_stats_proto_init() {
	if File_proto_stats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stats_proto_rawDesc), len(file_proto_stats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stats_proto_goTypes,
		DependencyIndexes: file_proto_stats_proto_depIdxs,
		MessageInfos:      file_proto_stats_proto_msgTypes,
	}.Build()
	File_proto_stats_proto = out.File
	file_proto_stats_proto_goTypes = nil
	file_proto_stats_proto_depIdxs = nil
}
